- name: Include service role
  ansible.builtin.include_role:
    name: "meta_service"
  vars:
    meta_service_name: "ssp"
    meta_service_fqdn: "password.{{ domain }}"
    meta_service_nginx_port: "3003"
    meta_service_certbot: true
    meta_service_nginx: true
    meta_service_tor: true
    meta_service_docker_compose: true
    meta_service_systemd_service: true

- name: Copy ssp environment file
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ base_dir }}/ssp/.env"
    mode: "0640"
