- name: Include service role
  ansible.builtin.include_role:
    name: "meta_service"
  vars:
    meta_service_name: "duplicati"
    meta_service_docker_compose: true
    meta_service_systemd_service: true
